### ISSUE TITLE
Installation using Spack?

### ISSUE THREAD

**Issue by ordinary-slim** [multiphenics/multiphenicsx#25]
The recommended way to install `dolfinx` on clusters is `Spack`. Is it possible to install `multiphenicsx` using `Spack`? Would it be possible to add simple to use instructions like [these ](https://github.com/FEniCS/dolfinx?tab=readme-ov-file#spack) in the Installation section?

**Comment by francesco-ballarin** [comment]
That's unlikely to happen, since it would mean that I would have to maintain a spack package as well, which is beyond my current time availability. Just install using pip in your existing spack environment: it will use the same compiler as the one that was used to compile dolfinx, which will make the two fully compatible with each other.
